### ISSUE TITLE
已是父级的分类，再设置父级分类的问题

### ISSUE THREAD

**Issue by JimchnZhou** [yanranxiaoxi/OpenNav#1]
### 提单版本：
Release v0.1.4

### 使用环境：
Google Chrome 108.0.5359.125（正式版本） （64 位）

#### 1. 创建三个分类，并在分类下添加链接：

分类一：嘉立创集团
>  - 嘉立创官网：https://www.jlc.com/
>  - 嘉立创SMT：https://www.jlcsmt.com/

分类二：嘉立创EDA

>  - 嘉立创EDA官网：https://lceda.cn/
>  - 嘉立创EDA_标准版：https://lceda.cn/editor
>  - 嘉立创EDA_专业版：https://pro.lceda.cn/editor

分类三：立创开源硬件平台

>  - Jimchn：https://oshwhub.com/jimchn
>  - 久治明千树汐：https://oshwhub.com/yanranxiaoxi

####  2. 创建完后前台页面如下图所示：
![image](https://user-images.githubusercontent.com/71536137/210946331-74941168-bb8e-4106-9666-ce7b2b8086bb.png)

#### 5. 设置完成后前台页面如下图所示：
![image](https://user-images.githubusercontent.com/71536137/210947525-466dc0b1-3f5c-4284-8343-85b6c7e79bb2.png)

#### 6. 由图可见，立创开源硬件平台及其链接在前台处于不可见状态。

全文结束

**Comment by yanranxiaoxi** [comment]
感谢提交，已在 https://github.com/yanranxiaoxi/OpenNav/commit/9f88736d52598d762b125ce6774683877689a12e 中修复
